services:
  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    container_name: backend
    restart: always
    env_file:
      - .env
    expose:
      - "80"
    volumes:
      - .:/app
    command: /bin/sh -c "pip install sqlalchemy psycopg2-binary python-dotenv && /start.sh"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend